In [ ]:
import torch

def mae(y_hat, y):
    return torch.mean(torch.abs((y_hat - y)))

def mse(y_hat, y):
    return torch.mean((y_hat-y) **2)

def sigmoid(X):
    return 1/(1+torch.exp(-X))

def softmax(z):
    scaled_z = z - torch.max(z)
    e_z = torch.exp(scaled_z)
    return e_z / torch.sum(e_z)

def BCE_loss(y_hat, y):
    return -(y * torch.log(y_hat)) + (1-y) *torch.log(1-y_hat)

def cross_entropy_loss()


X = torch.randint(0,5,(5,))
print(X)
print(sigmoid(X))
print(softmax(X))

tensor([3, 2, 3, 2, 0])
tensor([0.9526, 0.8808, 0.9526, 0.8808, 0.5000])
tensor([0.3590, 0.1321, 0.3590, 0.1321, 0.0179])
