In [15]:

import torch
#Create a 3×3 tensor of zeros and then a 3×3 tensor of ones.
zeros = torch.zeros((3,3))
ones = torch.ones((3,3))
print(zeros)
print(ones)

# Create a 1D tensor containing numbers from 0 to 9.
x = torch.arange(0,10)

# Create a 5×5 tensor with random numbers sampled from a normal distribution.
rand = torch.randn((5,5))
print(x)
print(rand)

# Create a tensor of shape (3,4) filled with the value 7.
y = torch.full((3,4), 7)
print(y)

y.type(dtype=torch.float32)
print(y)



tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[ 1.4050,  0.3940,  0.1996,  0.8774,  1.1553],
        [ 0.7211,  0.4359, -1.7307,  1.8903, -2.4007],
        [ 0.8101, -0.2098, -0.9450, -0.4381, -0.3999],
        [-0.2626,  0.7336, -0.2679,  0.5022, -1.8765],
        [ 0.5224, -0.8924,  1.7936,  0.4766, -0.5083]])
tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])
tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])


In [25]:
# 2. Tensor Indexing and Slicing
# Create a 4×5 tensor of random integers from 0–20.
rand  = torch.randint(0, 21, (4,5))
print(rand)

# Rows 1–3 and columns 2–4
print (rand[1:4, 2:5])

# Replace all elements greater than 10 with 0.
# This is called boolean masking
rand[rand > 10] = 0
print(f'Modified {rand}')

x = torch.arange(0,10)

# Create a 1D tensor of numbers from 0 to 9.
# Select all elements greater than 5.
# Select all even numbers.
# This example highlights basic selection
print(x[x > 5])
print(x[x %2 == 0])

print( '-----------------------------------')
# Element replacement
x = torch.randint(0,16, (3,4))
print(x)
x[x  > 10] = 0
print(x)

x[x%2 != 0] = -1
print(x)











tensor([[14,  9, 20, 19,  5],
        [13, 15,  9,  0, 12],
        [14,  0, 16, 16, 12],
        [ 3, 12, 13,  4,  5]])
tensor([[ 9,  0, 12],
        [16, 16, 12],
        [13,  4,  5]])
Modified tensor([[0, 9, 0, 0, 5],
        [0, 0, 9, 0, 0],
        [0, 0, 0, 0, 0],
        [3, 0, 0, 4, 5]])
tensor([6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])
-----------------------------------
tensor([[ 6,  7,  5, 15],
        [ 3,  8,  1,  6],
        [12,  6,  5, 10]])
tensor([[ 6,  7,  5,  0],
        [ 3,  8,  1,  6],
        [ 0,  6,  5, 10]])
tensor([[ 6, -1, -1,  0],
        [-1,  8, -1,  6],
        [ 0,  6, -1, 10]])


In [15]:
import torch
X = torch.rand((10,512))
print(X.shape)

R = torch.rand(512).reshape(1,-1)
print(R.shape)

D  = X - R

L2 = torch.sqrt(torch.sum(D **2, dim = 1))
print(L2.shape)

torch.Size([10, 512])
torch.Size([1, 512])
torch.Size([10])


In [21]:
F = torch.rand(4,32,8,8)
F[:,:16, :, :]
print(F[:,:16, :, :].shape)

f_map = F[1, 10, :, :]
print(f_map.shape)

b_mask = torch.full((4, 32, 8,8), False)
b_mask[F > 0.5] = True

t_mask = F[b_mask == True]
print(t_mask.shape)

b_mask = F > 0.5
print(b_mask)



torch.Size([4, 16, 8, 8])
torch.Size([8, 8])
torch.Size([4100])
tensor([[[[ True,  True,  True,  ..., False, False,  True],
          [ True, False,  True,  ..., False,  True, False],
          [ True, False, False,  ...,  True,  True,  True],
          ...,
          [False,  True, False,  ..., False,  True, False],
          [False,  True, False,  ...,  True,  True, False],
          [False, False,  True,  ...,  True,  True, False]],

         [[ True, False, False,  ..., False,  True, False],
          [False, False,  True,  ...,  True, False,  True],
          [ True, False, False,  ..., False, False,  True],
          ...,
          [False, False,  True,  ...,  True, False,  True],
          [ True, False,  True,  ...,  True,  True, False],
          [ True,  True, False,  ...,  True,  True, False]],

         [[ True,  True, False,  ...,  True, False, False],
          [False, False,  True,  ...,  True, False, False],
          [False, False, False,  ...,  True, False, False],
  

In [30]:
H = torch.rand((8,64,4,4))
H_flattened = H.view(H.shape[0], -1)
print(H_flattened)
H_flattened = H.view(8, -1)
print(H_flattened.shape)


H1 = torch.rand((64, 8, 4, 4))
H1 = H1.permute(1,0, 2,3)
print(H1.shape)
H1 = torch.transpose(H1, 1, 0)
print(H1.shape)

tensor([[0.2663, 0.0510, 0.8245,  ..., 0.1384, 0.6137, 0.8926],
        [0.5684, 0.6322, 0.2256,  ..., 0.3342, 0.0722, 0.1864],
        [0.6875, 0.7589, 0.2085,  ..., 0.7056, 0.1925, 0.4527],
        ...,
        [0.6655, 0.9580, 0.2896,  ..., 0.5455, 0.5238, 0.0440],
        [0.9025, 0.4967, 0.7958,  ..., 0.9648, 0.6136, 0.4792],
        [0.8613, 0.7813, 0.1249,  ..., 0.7454, 0.6347, 0.0625]])
torch.Size([8, 1024])
torch.Size([8, 64, 4, 4])
torch.Size([64, 8, 4, 4])
