In [5]:
# Sigmoid Activation Function
import torch

X = torch.randint(1,3, (1,3))
sigmoid = 1 / (1 + torch.exp(-X))
print(X)
print(sigmoid)


tensor([[1, 2, 2]])
tensor([[0.7311, 0.8808, 0.8808]])


In [7]:
z  =  torch.randint(1, 5, (1,10))
def softmax(z):
    shift_z = z - torch.max(z)
    exp_z = torch.exp(shift_z)
    return exp_z / torch.sum(exp_z)

print(z)
print(softmax(z))

tensor([[3, 1, 1, 1, 1, 3, 1, 4, 2, 2]])
tensor([[0.1631, 0.0221, 0.0221, 0.0221, 0.0221, 0.1631, 0.0221, 0.4434, 0.0600,
         0.0600]])
